In [2]:
import numpy as np

In [12]:
def mean_datasets(listCSV):
    n = len(listCSV)
    if n > 0:
        fileCsv = np.genfromtxt(listCSV[0], delimiter=',')
        for i in range(1, n):
            fileCsv += np.genfromtxt(listCSV[i], delimiter=',')
        mean = fileCsv/n
        return np.around(mean, 1)

In [14]:
if __name__ == '__main__':
    
    print(mean_datasets(['data1.csv', 'data2.csv', 'data3.csv']))
    print('------------------')
    print(mean_datasets(['data4.csv', 'data5.csv', 'data6.csv']))

[[11.  11.9 13. ]
 [ 9.5  6.8  9.4]
 [ 7.2 11.1 12.5]
 [ 8.8  7.3  9.2]
 [16.6 10.6 10.3]]
------------------
[[-2.9  2.6  0.6 -5.4]
 [-4.4 -0.7  0.7 -0.2]
 [-1.7  2.5 -8.7 -5.4]]
